### ISSUE TITLE
adidas AU site not working

### ISSUE THREAD

**Issue by William-Tahir** [yzyio/adidas-stock-checker#3]
maybe the client-ID is wrong

**Comment by bommels** [comment]
also make sure the product id exists on the adidas.com.au website.

**Comment by William-Tahir** [comment]
its a correct one, i took it directly from adidas website

**Comment by bommels** [comment]
What's the id?

**Comment by William-Tahir** [comment]
CM7827 at Adidas AU.

**Comment by bommels** [comment]
Looks like Adidas AU/NZ is blocking access to the client id lookup. You will get a time-out for a couple of seconds, but because in this time-out a request to the variant stock is already made this times-out too. I will fix this for AU because the client lookup doesn't work anyway, and nobody knows the current client id for AU.

Thanks for your feedback :)
